/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author Alex Rohleder
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form FuelStationMainFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPannel = new javax.swing.JTabbedPane();
        jPanelStation = new javax.swing.JPanel();
        jToggleButtonNew = new javax.swing.JToggleButton();
        jToggleButtonEdit = new javax.swing.JToggleButton();
        jToggleButtonRemove = new javax.swing.JToggleButton();
        jToggleButtonSearch = new javax.swing.JToggleButton();
        jSearchField = new javax.swing.JTextField();
        jTableScrollPanel = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        jPanelFuel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToggleButtonNew.setText("Novo");

        jToggleButtonEdit.setText("Editar");

        jToggleButtonRemove.setText("Remover");

        jToggleButtonSearch.setText("Procurar");

        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableScrollPanel.setViewportView(jTable);

        javax.swing.GroupLayout jPanelStationLayout = new javax.swing.GroupLayout(jPanelStation);
        jPanelStation.setLayout(jPanelStationLayout);
        jPanelStationLayout.setHorizontalGroup(
            jPanelStationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelStationLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelStationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTableScrollPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanelStationLayout.createSequentialGroup()
                        .addComponent(jToggleButtonNew)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButtonEdit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButtonRemove)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSearchField, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButtonSearch)))
                .addContainerGap())
        );
        jPanelStationLayout.setVerticalGroup(
            jPanelStationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelStationLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelStationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jToggleButtonNew)
                    .addComponent(jToggleButtonEdit)
                    .addComponent(jToggleButtonSearch)
                    .addComponent(jToggleButtonRemove)
                    .addComponent(jSearchField, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTableScrollPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPannel.addTab("Posto", jPanelStation);

        javax.swing.GroupLayout jPanelFuelLayout = new javax.swing.GroupLayout(jPanelFuel);
        jPanelFuel.setLayout(jPanelFuelLayout);
        jPanelFuelLayout.setHorizontalGroup(
            jPanelFuelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 395, Short.MAX_VALUE)
        );
        jPanelFuelLayout.setVerticalGroup(
            jPanelFuelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 326, Short.MAX_VALUE)
        );

        jTabbedPannel.addTab("Combustível", jPanelFuel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPannel, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPannel)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanelFuel;
    private javax.swing.JPanel jPanelStation;
    private javax.swing.JTextField jSearchField;
    private javax.swing.JTabbedPane jTabbedPannel;
    private javax.swing.JTable jTable;
    private javax.swing.JScrollPane jTableScrollPanel;
    private javax.swing.JToggleButton jToggleButtonEdit;
    private javax.swing.JToggleButton jToggleButtonNew;
    private javax.swing.JToggleButton jToggleButtonRemove;
    private javax.swing.JToggleButton jToggleButtonSearch;
    // End of variables declaration//GEN-END:variables
}
